# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 392e3692f9946d5ee91364e56551c12bb646e443aa3255cb14e9256fb1c0aace1ce4841cfb0f040030823158a87a3f088241a4fbd89c4bc3fdeccd4b871b5864

test:
  secret_key_base: 9936fcdcb347e4c6b046e7aa6c65e227074cad8b936379822d8550fafbea36b1563d0ebf43ca86ced210171c9b29b96a0f2a27ebdc014d91c829c1482bbefe59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
